---
to: components/<%= h.changeCase.pascal(name) %>/index.tsx
---
'use client'

import React from 'react'

interface <%= h.changeCase.pascal(name) %>Props {
  className?: string
}

export function <%= h.changeCase.pascal(name) %>({ className = '' }: <%= h.changeCase.pascal(name) %>Props) {
  return (
    <div className={`p-4 rounded-lg bg-card text-card-foreground ${className}`} data-testid="<%= h.changeCase.kebab(name) %>">
      <h3 className="text-lg font-semibold"><%= h.changeCase.pascal(name) %> Component</h3>
      <p className="text-sm text-muted-foreground">Generated by Hygen</p>
    </div>
  )
}
